#python data_processing/simplify_features.py
#python data_processing/infer_further_biodata.py
#python data_processing/create_segment_keyword_matrix.py
#python data_processing/map_indices_to_cover_terms.py
#python data_processing/infer_birkenau_survivors.py
#python data_processing/partition_interviews_into_metadata_groups.py
#python statistical_analysis/measure_strength_of_assoc_odds_ratio.py
python markov_modelling/train_markov_model.py
